
//LOGIN
POST http://localhost:3000/session/login
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

###

//LOGOUT
DELETE http://localhost:3000/session/logout

###

//CHECK SESSION

GET http://localhost:3000/session/
