// users

GET http://localhost:3000/api/users/

###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "admin",
    "password": "admin",
    "admin": "true"
}

###

PUT http://localhost:3000/api/users/admin
Content-Type: application/json

{
    "name": "admin",
    "password": "admin",
    "admin": "true"
}

###
DELETE http://localhost:3000/api/users/Fredrik