GET http://localhost:3000/api/assignments/

###

POST http://localhost:3000/api/assignments/
Content-Type: application/json

{
    "parentId": "1",
    "title": "Test title"
}

###

PUT http://localhost:3000/api/assignments/5eb2a2829199e73930d81118
Content-Type: application/json

{
    "parentId": "1",
    "title": "Testing 1212"
}

###
DELETE http://localhost:3000/api/assignments/5eb2a2829199e73930d81118


###

// subtasks

GET http://localhost:3000/api/subtasks/

###

POST http://localhost:3000/api/subtasks/
Content-Type: application/json

{
    "parentId": "1",
    "desc": "Test desc",
    "status": "Test status"
}

###

PUT http://localhost:3000/api/subtasks/5eb2b74342eac03b8cc3535a
Content-Type: application/json

{
    "parentId": "1",
    "desc": "Test ny",
    "status": "Test status"
}

###
DELETE http://localhost:3000/api/subtasks/5eb2b74342eac03b8cc3535a


###

// users

GET http://localhost:3000/api/users/

###

POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "Ohashat",
    "password": "123",
    "role": "Test role"
}

###

PUT http://localhost:3000/api/users/5eb2c7059c56a03ac8fc525a
Content-Type: application/json

{
    "name": "Fredrik",
    "password": "123",
    "role": "new"
}

###
DELETE http://localhost:3000/api/users/5eb2b83883d68034c0c1c903